import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/Components/Navbar';
import Footer from '@/Components/Footer';
import { ToastContainer } from 'react-toastify';
import AuthProvider from './Auth/AuthProvide';



const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <title>EduMaster</title>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="bg-gray-100">
            <div className="md:w-11/12 mx-auto">
              <Navbar></Navbar>
              <div className=" min-h-[calc(100vh-289px)] w-11/12 mx-auto">
                {children}
                <ToastContainer></ToastContainer>
              </div>
              <Footer></Footer>
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
